# Generated by Django 3.0.4 on 2020-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='images/')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=16)),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('Others', 'Others')], max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
                ('mother_name', models.CharField(max_length=120)),
                ('mother_job', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('father_phone', models.CharField(max_length=120)),
                ('father_job', models.CharField(max_length=120)),
                ('resident', models.CharField(max_length=25)),
                ('add1', models.CharField(max_length=120)),
                ('add2', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=8)),
                ('courses', models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Post Graduate', 'Post Graduate'), ('Diploma', 'Diploma')], max_length=25, null=True)),
                ('yours_choice', models.CharField(max_length=50)),
                ('yop1', models.CharField(max_length=4)),
                ('top1', models.CharField(max_length=3)),
                ('mop1', models.CharField(max_length=3)),
                ('pop1', models.CharField(max_length=3)),
                ('yop2', models.CharField(max_length=4)),
                ('top2', models.CharField(max_length=3)),
                ('mop2', models.CharField(max_length=3)),
                ('pop2', models.CharField(max_length=3)),
                ('sign', models.FileField(upload_to='images/')),
                ('mark1', models.FileField(upload_to='images/')),
                ('mark2', models.FileField(upload_to='images/')),
            ],
        ),
    ]
